# Single dimension NumPy Array


In [12]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [5]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [6]:
type(n1)

numpy.ndarray

# Multidimension NumPy array

In [19]:
import numpy as np
n2=np.array([[10,20,30],[10,80,90],[10,20,50]])
print(n2)


[[10 20 30]
 [10 80 90]
 [10 20 50]]


# initilize NumPy array with zeros

In [21]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
n4=np.zeros((9,9))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# initilization a array of matrix with full then

In [24]:
n5=np.full((3,3),9)
n5

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# initilization of NumPy array within a range.

In [25]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# initilization of NumpPy array with the skip numbers

In [26]:
n9=np.arange(1,10,2)
n9

array([1, 3, 5, 7, 9])

# initilization of NumpPy array with the random numbers

In [30]:
n11=np.random.randint(100,1000,10)
n11

array([319, 935, 808, 882, 722, 533, 987, 590, 704, 278])

# initilization the array shape changes in a fraction of seconds.

In [33]:
n12=np.array([[10,20,30],[10,30,50],[10,40,50],[10,90,60]])
n12

array([[10, 20, 30],
       [10, 30, 50],
       [10, 40, 50],
       [10, 90, 60]])

In [36]:
n12.shape


(4, 3)

In [40]:
n12.shape=(3,4)
n12

array([[10, 20, 30, 10],
       [30, 50, 10, 40],
       [50, 10, 90, 60]])

# joining Numpy array

In [41]:
a=np.array([10,20,30,40,50,60,70,80,90,100])
b=np.array([11,22,33,44,55,66,77,87,97,101])

In [42]:
np.vstack((a,b))

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [ 11,  22,  33,  44,  55,  66,  77,  87,  97, 101]])

In [43]:
np.hstack((a,b))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100,  11,  22,  33,
        44,  55,  66,  77,  87,  97, 101])

In [44]:
np.column_stack((a,b))

array([[ 10,  11],
       [ 20,  22],
       [ 30,  33],
       [ 40,  44],
       [ 50,  55],
       [ 60,  66],
       [ 70,  77],
       [ 80,  87],
       [ 90,  97],
       [100, 101]])

# Numpy intersection and difference

In [9]:
import numpy as np
x=np.array([10,20,30,40,50,60])

In [10]:
y=np.array([30,50,90,100,120,150])

In [12]:
intersection = np.intersect1d(x, y)

In [13]:
intersection

array([30, 50])

In [14]:
np.setdiff1d(x,y)

array([10, 20, 40, 60])

# Addition of NumPy Arrays

In [15]:
t=np.array([10,20])
s=np.array([30,40])

In [16]:
np.sum([t,s])

100

In [19]:
np.sum([t,s],axis=0)

array([40, 60])

# NumPy Array mathematics

In [20]:
p=np.array([10,20,30])

In [21]:
p+1


array([11, 21, 31])

In [22]:
p/2

array([ 5., 10., 15.])

In [23]:
p*2

array([20, 40, 60])

In [24]:
p-2

array([ 8, 18, 28])

# NumPy math functions

In [30]:
import numpy as np
nn=np.array([10,20,30,60])

In [31]:
np.mean(nn)

30.0

In [32]:
np.median(nn)

25.0

In [33]:
np.std(nn)

18.708286933869708

# saving and loading numpy array

In [34]:
import numpy as np
n11=np.array([10,20,30,40,50])

In [35]:
np.save('my_name',n11) 

In [36]:
!ls

Data_Sets  NumPy_Basics_to_Advance_for_DataScience.ipynb  my_name.npy


In [37]:
np.load('my_name.npy') 

array([10, 20, 30, 40, 50])

# Array Creation Methods

# 1. Array

### Uniform sample

In [39]:
np.random.uniform(5,10,size = 4)

array([6.78557099, 8.00595296, 5.64743056, 9.39807505])

In [40]:
np.random.uniform(size=4)

array([0.8476534 , 0.34311731, 0.67927537, 0.80313857])

In [41]:
np.random.randint(5,10,10)

array([9, 8, 7, 8, 9, 6, 8, 7, 6, 8])

In [42]:
np.random.random(3)

array([0.60488509, 0.74524548, 0.23246553])

# 2. Logspace

In [43]:
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

# 8. Array of zero

In [45]:
 np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# 11 Identity

In [46]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Arrary Operations

In [50]:
arr = np.array([1,3,3,4,5,6,7,8,9])
np.min(arr)

1

In [51]:
np.max(arr)

9

In [52]:
np.unique(arr, return_counts=True)

(array([1, 3, 4, 5, 6, 7, 8, 9]), array([1, 2, 1, 1, 1, 1, 1, 1]))

# Digitize

In [54]:
a = np.array([-0.9, 0.5, 0.9, 1, 1.2,1.4, 3.6, 4.7, 5.3])
bins = np.array([0,1,2,3,4])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 5, 5])

# Expand Dimensions

In [56]:
arr = np.array([8,14,1,8,10,32,43,34])
np.expand_dims(arr, axis=1)

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [10],
       [32],
       [43],
       [34]])

In [57]:
arr = np.array([8,14,1,8,10,32,43,34])
np.expand_dims(arr, axis=0)

array([[ 8, 14,  1,  8, 10, 32, 43, 34]])

# Squeeze 

In [58]:
arr = np.array([[8], [3], [5]])
np.squeeze(arr)

array([8, 3, 5])

# count non zero

In [59]:
a = np.array([0,0,0,1,1,1,0])
np.count_nonzero(a)

3

# Argwhere

In [60]:
a=np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]])

# Argmax and Argmin

In [61]:
arr= np.array([[0.12,0.60,0.79,0.45]])
np.argmax(arr)

2

In [62]:
np.argmin(arr)

0

# Sorting

In [63]:
arr = np.array([2,3,1,7,4])
np.sort(arr)

array([1, 2, 3, 4, 7])

# Abs

In [64]:
A = np.array([[1,-3,4] , [-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

In [66]:
np.shape(A)

(2, 3)

# Round

In [68]:
a = np.random.random(size=(3,4))
a

array([[0.56732883, 0.51561611, 0.93803754, 0.04184304],
       [0.93723313, 0.0549437 , 0.56122537, 0.88765212],
       [0.44300664, 0.80004318, 0.8767125 , 0.41878222]])

In [70]:
np.round(a,decimals=2)

array([[0.57, 0.52, 0.94, 0.04],
       [0.94, 0.05, 0.56, 0.89],
       [0.44, 0.8 , 0.88, 0.42]])

# clip

In [1]:
import numpy as np

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [2]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

# Replacing value inside array (Where)

In [3]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
np.where(a>5)

(array([2, 2, 2, 3, 3, 3]), array([0, 1, 2, 0, 1, 2]))

np.put(a, ind, v)

In [6]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
np.put(arr,[1,2],[6,7])
arr

array([1, 6, 7, 4, 5, 6])

# Copyto

In [10]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("Before arr1",arr1)
print("Before arr2",arr2)
np.copyto(arr1,arr2)
print("After arr1",arr1)
print("Before arr2",arr2)

Before arr1 [1 2 3]
Before arr2 [4 5 6]
After arr1 [4 5 6]
Before arr2 [4 5 6]


# Splitting

## Horizontal split

In [13]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A,2)

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

## Vertical split

In [15]:
A = np.array([[3,4,5,2],[6,7,2,6]])
np.vsplit(A,2)

[array([[3, 4, 5, 2]]), array([[6, 7, 2, 6]])]

# Repeat

In [17]:
np.repeat('2017',3)

array(['2017', '2017', '2017'], dtype='<U4')

# Einstein Sumation Conventions

In [20]:
a = np.array([1,2]).reshape(3,3)
b = np.array([3,4]).reshape(3,3)

np.einsum('ii->i',a)

ValueError: cannot reshape array of size 2 into shape (3,3)

In [22]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_1d = arr_2d.reshape(-1)
arr_1d = arr_2d.ravel()

print("Original 2D array:\n", arr_2d)
print("Reshaped 1D array:\n", arr_1d)

Original 2D array:
 [[1 2 3]
 [4 5 6]]
Reshaped 1D array:
 [1 2 3 4 5 6]


In [27]:
matrix1=np.array([[1,2,3],[5,4,6],[8,9,3]])
matrix2=np.array([[29,38,69],[54,43,62],[87,98,39]])

In [28]:
np.einsum('ij,jk',matrix1,matrix2)

array([[ 398,  418,  310],
       [ 883,  950,  827],
       [ 979,  985, 1227]])

In [29]:
np.einsum('ii',matrix1)

8

# Histogram

In [31]:
A = np.array([[3,4,5,2],
              [6,7,2,6]])
np.histogram(A)

(array([2, 0, 1, 0, 1, 0, 1, 0, 2, 1]),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))