# Single dimension NumPy Array


In [12]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [17]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [18]:
type(n1)

numpy.ndarray

# Multidimension NumPy array

In [19]:
import numpy as np
n2=np.array([[10,20,30],[10,80,90],[10,20,50]])
print(n2)


[[10 20 30]
 [10 80 90]
 [10 20 50]]


# initilize NumPy array with zeros

In [21]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
n4=np.zeros((9,9))
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# initilization a array of matrix with full then

In [24]:
n5=np.full((3,3),9)
n5

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# initilization of NumPy array within a range.

In [25]:
n6=np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# initilization of NumpPy array with the skip numbers

In [26]:
n9=np.arange(1,10,2)
n9

array([1, 3, 5, 7, 9])

# initilization of NumpPy array with the random numbers

In [30]:
n11=np.random.randint(100,1000,10)
n11

array([319, 935, 808, 882, 722, 533, 987, 590, 704, 278])

# initilization the array shape changes in a fraction of seconds.

In [33]:
n12=np.array([[10,20,30],[10,30,50],[10,40,50],[10,90,60]])
n12

array([[10, 20, 30],
       [10, 30, 50],
       [10, 40, 50],
       [10, 90, 60]])

In [36]:
n12.shape


(4, 3)

In [40]:
n12.shape=(3,4)
n12

array([[10, 20, 30, 10],
       [30, 50, 10, 40],
       [50, 10, 90, 60]])

# joining Numpy array

In [41]:
a=np.array([10,20,30,40,50,60,70,80,90,100])
b=np.array([11,22,33,44,55,66,77,87,97,101])

In [42]:
np.vstack((a,b))

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [ 11,  22,  33,  44,  55,  66,  77,  87,  97, 101]])

In [43]:
np.hstack((a,b))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100,  11,  22,  33,
        44,  55,  66,  77,  87,  97, 101])

In [44]:
np.column_stack((a,b))

array([[ 10,  11],
       [ 20,  22],
       [ 30,  33],
       [ 40,  44],
       [ 50,  55],
       [ 60,  66],
       [ 70,  77],
       [ 80,  87],
       [ 90,  97],
       [100, 101]])